apiVersion: v1
kind: ConfigMap
metadata:
  name: polaris-console-config
data:
  polaris-console.yaml: |-
    logger:
      RotateOutputPath: log/polaris-console.log
      RotationMaxSize: 500
      RotationMaxAge: 30
      RotationMaxBackups: 100
      level: info
    webServer:
      mode: "release"
      listenIP: "0.0.0.0"
      listenPort: 8080
      requestURL: "/naming/v1"
      monitorURL: "/api/v1"
      webPath: "web/dist/"
    polarisServer:
      address: "127.0.0.1:8090"
      polarisToken: "polaris@12345678"
    monitorServer:
      address: "polaris-prometheus:9090"
    oaAuthority:
      enableOAAuth: false
    hrData:
      enableHrData: false
