name: Standalone(Docker)

on:
  workflow_dispatch:
    inputs:
      server_version:
        description: "tag version for polaris"
        required: true
      console_version:
        description: "tag version for polaris-console"
        required: true

jobs:
  release:
    name: Release polaris standalone docker-image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.server_version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.POLARIS_DOCKER_NAME }}
          password: ${{ secrets.POLARIS_DOCKER_PASSWORD }}

      - name: Build
        id: build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          SERVER_VERSION: ${{ github.event.inputs.server_version }}
          CONSOLE_VERSION: ${{ github.event.inputs.console_version }}
        run: |
          set -e
          cd deploy/standalone
          POLARIS_GIT_PATH=https://github.com/polarismesh
          DIR_NAME=polaris-standalone-release_${SERVER_VERSION}.${GOOS}.${GOARCH}
          mkdir ${DIR_NAME}
          pushd ${DIR_NAME}
          SERVER_PKG_NAME=polaris-server-release_${SERVER_VERSION}.${GOOS}.${GOARCH}.zip
          wget -T10 -t3 ${POLARIS_GIT_PATH}/polaris/releases/download/${SERVER_VERSION}/${SERVER_PKG_NAME} --no-check-certificate
          CONSOLE_PKG_NAME=polaris-console-release_${CONSOLE_VERSION}.${GOOS}.${GOARCH}.zip
          wget -T10 -t3 ${POLARIS_GIT_PATH}/polaris-console/releases/download/${CONSOLE_VERSION}/${CONSOLE_PKG_NAME} --no-check-certificate

          wget -T10 -t3 https://github.com/prometheus/prometheus/releases/download/v2.28.0/prometheus-2.28.0.${GOOS}-${GOARCH}.tar.gz
          wget -T10 -t3 https://github.com/prometheus/pushgateway/releases/download/v1.4.1/pushgateway-1.4.1.${GOOS}-${GOARCH}.tar.gz
          mv ../vm/install-${GOOS}.sh ./install.sh
          mv ../vm/uninstall-${GOOS}.sh ./uninstall.sh
          mv ../vm/port.properties ./port.properties
          mv ../vm/Dockerfile ./Dockerfile

          mv ${SERVER_PKG_NAME} polaris-server.zip
          mv ${CONSOLE_PKG_NAME} polaris-console.zip
          mv prometheus-2.28.0.${GOOS}-${GOARCH}.tar.gz prometheus.tar.gz

          docker_repository="polarismesh"
          docker_image="polaris-server-standalone"
          docker_tag=${SERVER_VERSION}

          docker build --network=host -t ${docker_repository}/${docker_image}:${docker_tag} ./

          docker push ${docker_repository}/${docker_image}:${docker_tag}
          docker tag ${docker_repository}/${docker_image}:${docker_tag} ${docker_repository}/${docker_image}:latest
          docker push ${docker_repository}/${docker_image}:latest
