name: DockerImage

on:
  workflow_dispatch:
    inputs:
      polaris_tag:
        description: 'tag for polaris'
        required: true
      docker_username:
        description: 'docker username for login'
        required: true
      docker_password:
        description: 'docker password for login'
        required: true

jobs:
  release:
    name: Release Polaris Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.polaris_tag }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.5
          
      - name: Build Server
        id: build-server
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          DOCKER_REPOSITORY: polarismesh/polaris-server
          DOCKER_TAG: ${{ github.event.inputs.polaris_tag }}
          DOCKER_USER: ${{ github.event.inputs.docker_username }}
          DOCKER_PASS: ${{ github.event.inputs.docker_password }}
        run: |
          ls -lstrh
          bash build_docker.sh ${DOCKER_REPOSITORY} ${DOCKER_TAG} ${DOCKER_USER} ${DOCKER_PASS}

      - name: Build Prometheus
        id: build-prom
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          DOCKER_REPOSITORY: polarismesh/prometheus
          DOCKER_TAG: ${{ github.event.inputs.polaris_tag }}
          DOCKER_USER: ${{ github.event.inputs.docker_username }}
          DOCKER_PASS: ${{ github.event.inputs.docker_password }}
        run: |
          cd deploy/docker/prometheus
          ls -lstrh
          bash build_docker_prom.sh ${DOCKER_REPOSITORY} ${DOCKER_TAG} ${DOCKER_USER} ${DOCKER_PASS}
